In [4]:
import tensorflow as tf
print("Tensorflowversion:", tf.__version__)

Tensorflowversion: 2.12.0


In [6]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
import matplotlib.pyplot as plt

In [13]:
mn=tf.keras.datasets.mnist

In [15]:
(x_train, y_train), (x_test, y_test) = mn.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.86574376, -0.23583359,  0.5248147 ,  0.44344738, -0.2131925 ,
         0.50442004, -0.8100031 , -0.12436156, -0.44375026, -0.11563111]],
      dtype=float32)

In [18]:
tf.nn.softmax(predictions).numpy()

array([[0.20246343, 0.067288  , 0.14397365, 0.13272281, 0.06882886,
        0.14106709, 0.03789474, 0.07522277, 0.05465635, 0.07588238]],
      dtype=float32)

In [19]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

1.9585197

In [21]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, epochs=8)

Epoch 1/8
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0397 - accuracy: 0.9871
Epoch 2/8
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0354 - accuracy: 0.9878
Epoch 3/8
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0350 - accuracy: 0.9875
Epoch 4/8
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0327 - accuracy: 0.9890
Epoch 5/8
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0315 - accuracy: 0.9896
Epoch 6/8
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0291 - accuracy: 0.9898
Epoch 7/8
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0289 - accuracy: 0.9903
Epoch 8/8
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0269 - accuracy: 0.9906


In [25]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 2s - loss: 0.0755 - accuracy: 0.9798 - 2s/epoch - 6ms/step


[0.07548680156469345, 0.9797999858856201]

In [26]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [27]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.2466985e-10, 7.8751831e-14, 1.7269540e-11, 8.6042628e-06,
        1.3659022e-17, 7.8942047e-11, 2.1856174e-21, 9.9999142e-01,
        4.5532278e-10, 6.5676029e-09],
       [9.5507534e-12, 2.4918232e-09, 1.0000000e+00, 1.3910941e-13,
        3.5176116e-37, 2.3553300e-13, 6.4538749e-16, 3.8196911e-27,
        6.8858008e-17, 4.6163008e-24],
       [3.4216967e-12, 9.9999428e-01, 1.7945063e-06, 2.9055562e-09,
        2.1871737e-07, 1.8144051e-09, 3.0565064e-09, 1.5914283e-06,
        2.0869870e-06, 1.2582804e-11],
       [9.9999905e-01, 8.4504970e-18, 8.4195898e-07, 2.4241451e-13,
        2.0983940e-14, 5.2065068e-11, 1.3223868e-07, 4.3861918e-11,
        8.8623873e-13, 2.6827948e-08],
       [5.0515570e-09, 2.9439297e-20, 2.5794075e-10, 2.5909103e-14,
        9.9992907e-01, 8.0600743e-12, 2.4771936e-09, 5.1263874e-07,
        7.3586470e-11, 7.0399292e-05]], dtype=float32)>